module-template: ! 'module MODULE_NAME where

'
extensions: {}
environment: default
version: 1
ghc-args:
- -hide-all-packages
- -package
- fay
- -package
- fay-base
- -package
- ide-config
- -Wall
- -DFAY
- -XNoImplicitPrelude
excluded-modules: []
